### ISSUE TITLE
编辑器原型

### ISSUE THREAD

**Issue by testacount1** [CNMan/UnicodeCJK-WuBi06#20]
基于https://www.v2ex.com/t/490269

源码在: https://gist.github.com/testacount1/156caddfa8bb2de5c8acb26f53718f00
本人不大用Python, UI更不在行(没有排版). 希望抛砖引玉吧. 

开发的时候把测试图片放在了同目录的images目录下
运行`python 主程序.py`(Python 3)效果如下. 
支持修改第一条的86版值, 导出文件. 上/下一条, 搜索尚不支持. 使用的测试文件只包含CJK-A的最前两条记录.

代码用的是中文命名, 注释中有主要参考的文档. 有兴趣的话希望先自行试试添加余下功能.

![screen shot 2018-09-17 at 4 24 14 pm](https://user-images.githubusercontent.com/12469353/45655645-2e554100-ba96-11e8-82cd-b7c92d242b38.png)

**Comment by gwokming** [comment]
膜拜

**Comment by CNMan** [comment]
@testacount1 多谢

**Comment by nobodxbodon** [comment]
@CNMan 如果打算在此基础上改进, 不妨建个'工具'之类的文件夹, 把这个脚本版本控制一下. 方便看到最新进展, 顺便写个说明, 写一下还需要的功能. 也许会有空跟进参与.

**Comment by CNMan** [comment]
@nobodxbodon 1楼是你的小号吧？提交个Pull request到 https://github.com/CNMan/UnicodeCJK-WuBi
字体图片我添加上了，你直接提交到主目录吧，命名为`wubicodeeditor.py`
我不会编程，估计需要你抽空完成
