### ISSUE TITLE
包含“韱”的几个字的编码是否修改错了？

### ISSUE THREAD

**Issue by panqiincs** [CNMan/UnicodeCJK-WuBi06#45]
最近修改了如下几个字的编码：籤、纖、虃、襳、韱、㡨 

韱的末笔为点，在y键位上，应该没错呀。

**Comment by panqiincs** [comment]
我明白了，“韱”的拆法类似于“或”，而不是“武”。

**Comment by CNMan** [comment]
涉及原版（即CJK和CJK－A）的修改一般 #1 都有说明
