### ISSUE TITLE
你好，我创建了一个新的码表项目

### ISSUE THREAD

**Issue by beavailable** [CNMan/UnicodeCJK-WuBi06#47]
这个项目是基于你的 https://github.com/CNMan/rime-data 项目里的一个新世纪通用码表而创建的，特此感谢。

我对码表做了部分修改，同时转换成了 fcitx5 可以使用的码表，并打算单独维护，可以的话，请加入本项目的资源库。

项目地址：https://github.com/beavailable/better-wubi

**Comment by CNMan** [comment]
你进QQ群38021162（新世纪五笔）和`Ⅴ ⑤修改姓名` （即 @IT1187541749 ）交流一下，他在 #1 中提到的魔改方案应该已经完成了。
